# Generated by Django 2.2.3 on 2019-07-20 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mymeals', '0004_auto_20190720_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
